services:
  tg-to-115:
    build: .
    container_name: tg-to-115
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./config:/app/config
      - /vol2/1000/media/tg_videos:/app/downloads
    environment:
      - TZ=Asia/Shanghai
    networks:
      - docker_isweet

networks:
  docker_isweet:
    external: true
